### ISSUE TITLE
update for NG 10 and NS7

### ISSUE THREAD

**Issue by aquinn637** [chronogolf/nativescript-store-update#32]
NativeScript 7 is out and Angular 10 is out.

I upgraded my project to NS7 and I get this error:

```
System.err: 
System.err: StackTrace: 
System.err: push.../node_modules/nativescript-store-update/store-update.common.js.StoreUpdateCommon._init(file: node_modules/nativescript-store-update/store-update.common.js:120:0)
System.err: 	at StoreUpdateCommon(file: node_modules/nativescript-store-update/store-update.common.js:25:0)
System.err: 	at push.../node_modules/nativescript-store-update/store-update.js.StoreUpdate.init(file: node_modules/nativescript-store-update/store-update.android.js:21:0)
System.err: 	at (file:///data/data/org.nativescript.SelfServiceApp/files/app/bundle.js:4794:41)
System.err: 	at ./main.ts(file:///data/data/org.nativescript.SelfServiceApp/files/app/bundle.js:4814:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at checkDeferredModules(file: src/webpack/bootstrap:43:0)
System.err: 	at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
System.err: 	at (file:///data/data/org.nativescript.SelfServiceApp/files/app/bundle.js:2:57)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'language' of undefined
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:689)
System.err: 	at com.tns.Runtime.run(Runtime.java:681)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
System.err: 	at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7145)
System.err: 	... 9 more
```
Can we update this plugin?

**Comment by andrewm-mitchells** [comment]
Any update on this issue? Or anyone know of an alternative?

**Comment by andrew-mykhalchuk** [comment]
Now we need someone to create a release from recently merged PR and publish it on NPM so people can start utilizing working version.
